version: '2'
services:
    resavision-app:
        image: resavision
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://resavision-mysql:3306/resavision?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=resavision-elasticsearch:9300
        ports:
            - 8080:8080
    resavision-mysql:
        extends:
            file: mysql.yml
            service: resavision-mysql
    resavision-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: resavision-elasticsearch
